name: Build & Deploy Frontend to GitHub Pages

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      build-path: ${{ steps.set-path.outputs.path }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Set build path output
        id: set-path
        run: |
          # change 'build' below to 'dist' or your build folder if needed
          echo "path=dist" >> $GITHUB_OUTPUT


  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    steps:
      - name: Upload production build
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ needs.build.outputs.build-path }}

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
